# Generated by Django 5.2 on 2025-07-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
