# Generated by Django 5.2 on 2025-07-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rentagreement_rentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='virtual_tour_video',
            field=models.URLField(blank=True, help_text='YouTube video link of flat tour', null=True),
        ),
    ]
